baseURL: 'http://rabbitisland.dev'
languageCode: 'en-us'
title: 'Rabbit Island'
theme: 'PaperMod'

googleAnalytics: G-DKYY4HJSRB
enableRobotsTxt: true

permalinks:
  posts: "/:filename"

minify:
    disableXML: true
    minifyOutput: true

params:
  env: production
  title: "EmergencyFood"
  description: "thoughts on web development, cybersecurity and life"
  keywords: ['web development', 'cybersecurity', 'software development', 'linux']
  author: Yu Guozhong (俞国忠)
  DateFormat: "January 2, 2006"
  defaultTheme: dark

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: true

  homeInfoParams:
    Title: "Hi there! I'm just a random traveller on the internet."
    Content: "Thoughts on software development, cybersecurity and privacy."

  socialIcons:
    - name: github
      url: "https://github.com/gohanko"
    - name: linkedin
      url: "https://www.linkedin.com/in/gohanko/"
    - name: telegram
      url: "https://t.me/emergencyfood"
    - name: rss
      url: /index.xml

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: about
      name: about
      url: /about/
      weight: 30
