baseURL: 'http://emergencyfood.dev'
languageCode: 'en-us'
title: 'EmergencyFood'
theme: 'PaperMod'

permalinks:
  posts: "/:filename"

menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: about
      name: about
      url: /about/
      weight: 30


params:
  env: production
  title: "EmergencyFood"
  description: ""
  keywords: []
  author: EmergencyFood
  DateFormat: "January 2, 2006"
  defaultTheme: dark

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true
    disableFingerprinting: true

  homeInfoParams:
    Title: "Hi there!"
    Content: "Placeholder!"

  socialIcons:
    - name: github
      url: "https://github.com/gohanko"
    - name: linkedin
      url: "https://www.linkedin.com/in/gohanko/"
    - name: telegram
      url: "https://t.me/emergencyfood"
    - name: rss
      url: /index.xml

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page